name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "54.0"
      - name: Download geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
          mkdir geckodriver
          tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
          echo "$PWD/geckodriver" >> $GITHUB_PATH
        shell: bash
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6.6"
          bundler-cache: true
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "4.0"
          mongodb-db: slack-ruby-bot-server-stripe_sample_test
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: bundle exec rake
